name: build and test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: install gtk dependencies
      run: |
        sudo apt update
        sudo apt install -y libgtk-3-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose --all-targets
  build-windows:
    runs-on: windows-latest
    steps:
    - name: install rust i686
      run: rustup toolchain install stable-i686-msvc
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose --all-targets
    - name: Build 32
      run: cargo +stable-i686-msvc build --all-targets
    - name: Run tests 32
      run: cargo +stable-i686-msvc test --all-targets